//
//  SettingsInteractor.swift
//  PomodoroApp
//
//  Created Ацамаз on 09/01/2019.
//  Copyright © 2019 a.s.bitsoev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SettingsInteractor: SettingsInteractorProtocol {

    weak var presenter: SettingsPresenterProtocol?
    
    
    func setTheme(_ theme: Themes) {
        
        UserDefaults.standard.set(theme.rawValue, forKey: "theme")
        
        NotificationCenter.default.post(name: NSNotification.Name("setTheme"), object: nil)
        
        UIApplication.shared.setAlternateIconName(MyTheme(theme: theme).iconName) { (error) in
            print("\n\n\(error?.localizedDescription)")
        }
        
    }
    
    
    // TOTAL TIME SPENT
    func totalTimeSpent() -> Int {

        var totalTime = 0
        
        let arr = CoreDataService.standard.arrayofTasks()
        
        for task in arr {
            
            totalTime += Int(task.timeSpent)
            
        }
        
        return totalTime
        
    }
    
    // MAIN TASK
    func mainTask() -> Task? {
        
        let arr = CoreDataService.standard.arrayofTasks()
        
        let sortedArr = arr.sorted { (task1, task2) -> Bool in
            task1.timeSpent < task2.timeSpent
        }
        
        return sortedArr.last
        
    }
    
    
}




// ONLY NUMBERS
extension String {
    
    func onlyNumbers() -> String {
        
        var string = ""
        
        for c in self {
            
            if ["0","1","2","3","4","5","6","7","8","9"].contains(c) {
                
                string.append(c)
                
            }
            
        }
        
        return string
        
    }
    
}
