//
//  SettingsProtocols.swift
//  PomodoroApp
//
//  Created Ацамаз on 09/01/2019.
//  Copyright © 2019 a.s.bitsoev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SettingsWireframeProtocol: class {

}
//MARK: Presenter -
protocol SettingsPresenterProtocol: class {
    
    func setTheme(_ theme: Themes)
    func preparedTotalTimeSpent() -> String
    func mainTaskName() -> String
    
}

//MARK: Interactor -
protocol SettingsInteractorProtocol: class {

  var presenter: SettingsPresenterProtocol?  { get set }
    
    func setTheme(_ theme: Themes)
    func totalTimeSpent() -> Int
    func mainTask() -> Task?
    
}

//MARK: View -
protocol SettingsViewProtocol: class {

  var presenter: SettingsPresenterProtocol?  { get set }
}
